language: node_js
node_js:
  - "stable"

matrix:
  include:
  - os: linux
  - os: osx

script:
  - yarn install
  - yarn build-storybook
  - yarn lerna:test:cov
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       yarn coveralls;
     fi
    '

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
