language: node_js
node_js:
  - "stable"
script:
  - yarn install
  - yarn lerna:test:cov
  - yarn coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
