[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Server = "Pismo"
    Referrer-policy = "same-origin"